<a href="https://colab.research.google.com/github/salazarcristian1014/restaurant-cancelation-project/blob/main/Analysis_restaurant_bookings_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
#Hacemos la lectura de nuestros datos que fueron limpiados y organizados previamente para dar inicio con nuestro analisis

df = pd.read_csv('datos_reservas_idilico_limpio.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2982 entries, 0 to 2981
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   codigo              2982 non-null   int64
 1   sucursal            2982 non-null   object
 2   fecha               2982 non-null   object
 3   hora                2982 non-null   object
 4   Número de personas  2982 non-null   int64
 5   Nuevo usuario       2982 non-null   object
 6   nombre              2982 non-null   object
 7   email               2894 non-null   object
 8   código de teléfono  2981 non-null   object
 9   telefono_completo   2981 non-null   object
 10  estado              2982 non-null   object
 11  Comentario Reserva  140 non-null    object
 12  origen              2982 non-null   object
 13  Fecha de creación   2982 non-null   object
 14  Cobros              355 non-null    float64
 15  Pagado              2982 non-null   object
 16  Pagados             2982 non-null   object
dtypes: float64(1), int64(2), object(14)
memory usage: 396.2+ KB

In [22]:
#Revisamos que toda la informacion cargue correctamente

df.head()

,codigo,sucursal,fecha,hora,Número de personas,Nuevo usuario,nombre,email,código de teléfono,telefono_completo,estado,Comentario Reserva,origen,Fecha de creación,Cobros,Pagado,Pagados
0,2002222,Restaurante Idilico,2025-01-02,2026-03-25 20:30:00,2,Sí,Francesca Grimaldi,f.schibonigrimaldi@gmail.com,39,+393288317828,Cancelada,NaN,Cluvi,03-12-2024,NaN,Sí,No
1,2025131,Restaurante Idilico,2025-01-04,2026-03-25 20:30:00,2,No,Samantha Vassor,samvassor@gmail.com,1,+15616939883,Cancelada,NaN,google,16-12-2024,NaN,Sí,No
2,2007791,Restaurante Idilico,2025-01-04,2026-03-25 20:30:00,2,Sí,Melani Kerslake,mkerslake@msn.com,1,+14252757101,Cancelada,NaN,google,06-12-2024,NaN,Sí,No
3,2008810,Restaurante Idilico,2025-01-06,2026-03-25 18:30:00,1,Sí,Michael Lowe,michael.lowe@tefball.com,1,+17783503113,Cancelada,NaN,Cluvi,06-12-2024,NaN,Sí,No
4,2009405,Restaurante Idilico,2025-01-06,2026-03-25 18:30:00,2,Sí,Michelle yu,michelleyu94@gmail.com,1,+14168785661,Cancelada,NaN,Cluvi,06-12-2024,NaN,Sí,No

In [23]:
df['sucursal'].value_counts()

sucursal
Restaurante Idilico    2627
Mesas Del Chef          355
Name: count, dtype: int64

In [37]:
# que cantidad de reservas pertenecen a cada sucursal ?

# Extraemos las fechas
inicio = df['fecha'].min()
fin = df['fecha'].max()

# Hacemos el conteo de las reservas
conteo = df['sucursal'].value_counts()
conteo_porcentajes = df['sucursal'].value_counts(normalize=True) * 100

# Guardamos los totales por su posición
total = len(df)
idilico = conteo.iloc[0]
chef = conteo.iloc[1]
porc_idilico = conteo_porcentajes.iloc[0]
porc_chef = conteo_porcentajes.iloc[1]

print(f"Desde la fecha: {inicio} hasta: {fin} Se registraron un total de: {total} reservas.\nDe las cuales {idilico} ({porc_idilico:.1f}%) pertenecen a Restaurante Idílico y {chef} ({porc_chef:.1f}%) a Mesas del Chef.")

Desde la fecha: 2025-01-02 hasta: 2026-02-28 Se registraron un total de: 2982 reservas.
De las cuales 2627 (88.1%) pertenecen a Restaurante Idílico y 355 (11.9%) a Mesas del Chef.

In [46]:
# Cual fue el numero de clientes que reservaron por sucursal ?

df.groupby('sucursal')['Número de personas'].sum()
personas_por_sucursal = df.groupby('sucursal')['Número de personas'].sum()
total_personas_idilico = personas_por_sucursal.iloc[1]
total_personas_chef = personas_por_sucursal.iloc[0]
total_sucursales = sum(personas_por_sucursal)

print(f"Desde la fecha: {inicio} Hasta: {fin} reservaron un total de: {total_sucursales} personas\n de las cuales {total_personas_idilico} reservaron en la sucursal Idilico para menu a la carta y\n {total_personas_chef} reservaron en la sucursal mesas del chef para menu degustación")

Desde la fecha: 2025-01-02 Hasta: 2026-02-28 reservaron un total de: 8193 personas
 de las cuales 7307 reservaron en la sucursal Idilico para menu a la carta y
 886 reservaron en la sucursal mesas del chef para menu degustación

In [ ]:
# Cual es la tasa de cancelacion por sucursal ?