<a href="https://colab.research.google.com/github/salazarcristian1014/restaurant-cancelation-project/blob/main/Limpieza_Datos_Automatizacion_Reservas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
import pandas as pd
import numpy as np
from google.colab import files

# Instrucción para subir el archivo de Cluvi desde tu computador
print("Por favor, selecciona el archivo Excel o CSV de Cluvi:")
uploaded = files.upload()

Por favor, selecciona el archivo Excel o CSV de Cluvi:

Saving reporte-servicios-69cb10c72ac7363b179360f3-032476cd-1f55-4dbe-aa0c-7edd7f13598c (1).xlsx to reporte-servicios-69cb10c72ac7363b179360f3-032476cd-1f55-4dbe-aa0c-7edd7f13598c (1) (1).xlsx

In [41]:
# leemos el archivo
df = pd.read_excel('reporte-servicios-69cb10c72ac7363b179360f3-032476cd-1f55-4dbe-aa0c-7edd7f13598c (1).xlsx')

# Visualizamos las primeras filas para entender la estructura
df.head()

,codigo,sucursal,fecha,hora,Número de personas,Nuevo usuario,nombre,email,código de teléfono,teléfono,...,FE billingId,acepta términos y condiciones de Cluvi,fecha de aceptación de términos y condiciones de Cluvi,hora de aceptación de términos y condiciones de Cluvi,términos y condiciones de Cluvi,acepta términos y condiciones del restaurante,fecha de aceptación de términos y condiciones del restaurante,hora de aceptación de términos y condiciones del restaurante,términos y condiciones del restaurante,soporte de pago
0,2791814,Restaurante Idilico,2026-03-24,19:00,2,Sí,Cole Taylor,colemt5@gmail.com,1,5412327688,...,NaN,Sí,08-03-2026,19:21:52,https://restaurante-idilico.cluvi.co/POLITICAD...,Sí,08-03-2026,19:21:52,<p><strong>** El tiempo de tolerancia es máxim...,NaN
1,2818745,Restaurante Idilico,2026-03-24,19:00,6,Sí,Mariana Ramos,marianaramosmonge@gmail.com,57,3145287483,...,NaN,Sí,24-03-2026,15:17:19,https://restaurante-idilico.cluvi.co/POLITICAD...,Sí,24-03-2026,15:17:19,<p><strong>** El tiempo de tolerancia es máxim...,NaN
2,2810950,Restaurante Idilico,2026-03-24,19:00,5,Sí,Era Iyer,eraiyer@gmail.com,1,4087185461,...,NaN,Sí,20-03-2026,12:58:12,https://admin.cluvi.com/privacy-policies,No,20-03-2026,12:58:12,NaN,NaN
3,2811433,Mesas Del Chef,2026-03-24,19:30,2,Sí,Corine Van den Berg,rcberg4ever@gmail.com,31,655716727,...,NaN,Sí,20-03-2026,16:36:58,https://restaurante-idilico.cluvi.co/POLITICAD...,Sí,20-03-2026,16:36:58,<p>Las mesas del chef están ubicadas en un peq...,NaN
4,2811353,Mesas Del Chef,2026-03-24,19:30,2,Sí,Corine Van den Berg,rcberg4ever@gmail.com,57,3112189601,...,NaN,Sí,20-03-2026,15:59:21,https://restaurante-idilico.cluvi.co/POLITICAD...,Sí,20-03-2026,15:59:21,<p>Las mesas del chef están ubicadas en un peq...,NaN

In [42]:
#Revisamos que tipo de colmnas tenemos
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42 entries, 0 to 41
Data columns (total 55 columns):
 #   Column                                                         Non-Null Count  Dtype
---  ------                                                         --------------  -----
 0   codigo                                                         42 non-null     int64
 1   sucursal                                                       42 non-null     object
 2   fecha                                                          42 non-null     object
 3   hora                                                           42 non-null     object
 4   Número de personas                                             42 non-null     int64
 5   Nuevo usuario                                                  42 non-null     object
 6   nombre                                                         42 non-null     object
 7   email                                                          40 non-null     object
 8   código de teléfono                                             42 non-null     int64
 9   teléfono                                                       42 non-null     int64
 10  motivo                                                         0 non-null      float64
 11  estado                                                         42 non-null     object
 12  observación                                                    3 non-null      object
 13  Comentario Reserva                                             8 non-null      object
 14  Tipo documento                                                 0 non-null      float64
 15  Número Documento                                               0 non-null      float64
 16  Género                                                         0 non-null      float64
 17  Observación al cancelar                                        1 non-null      object
 18  Tipo de reserva                                                42 non-null     object
 19  origen                                                         42 non-null     object
 20  llego                                                          0 non-null      float64
 21  fecha de cumpleaños                                            0 non-null      float64
 22  factura_numero                                                 0 non-null      float64
 23  manual_table                                                   0 non-null      float64
 24  config_table                                                   0 non-null      float64
 25  salió                                                          42 non-null     object
 26  Fecha de creación                                              42 non-null     object
 27  Hora de creación                                               42 non-null     object
 28  fecha pago                                                     3 non-null      object
 29  hora pago                                                      3 non-null      object
 30  Fecha de cancelación                                           10 non-null     object
 31  Hora de cancelación                                            10 non-null     object
 32  Responsable                                                    0 non-null      float64
 33  Cobros                                                         9 non-null      object
 34  Pagado                                                         42 non-null     object
 35  Productos                                                      0 non-null      float64
 36  Servicio                                                       0 non-null      float64
 37  Zona                                                           0 non-null      float64
 38  Identificador en enlace                                        0 non-null      float64
 39  Alergias                                                       5 non-null      object
 40  Adjuntos                                                       0 non-null      float64
 41  FE documento                                                   2 non-null      float64
 42  FE Nombre                                                      2 non-null      object
 43  FE email                                                       2 non-null      object
 44  FE teléfono                                                    7 non-null      object
 45  FE billingId                                                   2 non-null      float64
 46  acepta términos y condiciones de Cluvi                         42 non-null     object
 47  fecha de aceptación de términos y condiciones de Cluvi         42 non-null     object
 48  hora de aceptación de términos y condiciones de Cluvi          42 non-null     object
 49  términos y condiciones de Cluvi                                37 non-null     object
 50  acepta términos y condiciones del restaurante                  42 non-null     object
 51  fecha de aceptación de términos y condiciones del restaurante  42 non-null     object
 52  hora de aceptación de términos y condiciones del restaurante   42 non-null     object
 53  términos y condiciones del restaurante                         26 non-null     object
 54  soporte de pago                                                0 non-null      float64
dtypes: float64(18), int64(4), object(33)
memory usage: 18.2+ KB

In [43]:
df['estado'].value_counts()

estado
Re Confirmada    27
Cancelada         9
Confirmada        4
Pendiente         1
Anulada           1
Name: count, dtype: int64

In [44]:
# Convertimos las reservas a 2 tipos de estado = 'Confirmadas' y 'Cancelada'
df['estado'] = df['estado'].replace({
    'Anulada': 'Cancelada',
    'Re Confirmada': 'Confirmada',
    'Pendiente': 'Confirmada'
})

In [45]:
df['estado'].value_counts()

estado
Confirmada    32
Cancelada     10
Name: count, dtype: int64

In [46]:
# Debido a fallas que ya mostro el sistema en la fase 1 de este proyecto copiamos el codigo por si volvemos a tener problemas con el estado,
# lo que hacemos aca es que si hay una fecha de cancelacion el estado pasa a ser 'Cancelado'

df.loc[df['Fecha de cancelación'].notna(), 'estado'] = 'Cancelada'

In [49]:
# Nos quedamos solo con las columnas que usaremos para el proceso de automatizacion

df = df[['nombre' , 'email' , 'estado' , 'sucursal' , 'fecha', 'acepta términos y condiciones de Cluvi', 'acepta términos y condiciones del restaurante']]

In [51]:
# Eliminamos reservas de personas que resevaron 2 veces para el mismo dia y cancelaron una reserva pero si visitaron el restaurante.

# Ordenar para que 'Confirmada' quede arriba
df = df.sort_values(by='estado', ascending=False)

# Eliminar duplicados reteniendo la primera coincidencia
df = df.drop_duplicates(subset=['fecha', 'email'], keep='first')

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 40 entries, 0 to 41
Data columns (total 7 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   nombre                                         40 non-null     object
 1   email                                          39 non-null     object
 2   estado                                         40 non-null     object
 3   sucursal                                       40 non-null     object
 4   fecha                                          40 non-null     object
 5   acepta términos y condiciones de Cluvi         40 non-null     object
 6   acepta términos y condiciones del restaurante  40 non-null     object
dtypes: object(7)
memory usage: 2.5+ KB

In [54]:
# Creamos el nuevo archivo para la automatizacion con la condicional de que solo tome las reservas en estado cancelada y que aceptaron los terminos y condiciones
# para el tratamiento de datos.

df_cancelados = df[(df['estado'] == 'Cancelada') & (df['acepta términos y condiciones de Cluvi'] == 'Sí') & (df['acepta términos y condiciones del restaurante'] == 'Sí')]

In [58]:
df_cancelados['fecha'] = pd.to_datetime(df_cancelados['fecha'])

/tmp/ipykernel_1308/2500429467.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cancelados['fecha'] = pd.to_datetime(df_cancelados['fecha'])

In [59]:
# Exportar el archivo
df_cancelados.to_excel('cancelados_automatizacion.xlsx', index=False)

# Descargarlo automáticamente al computador
from google.colab import files
files.download('cancelados_automatizacion.xlsx')